name: Update Fuel Prices
on:
  schedule:
    - cron: '0 * * * *' # S'exécute toutes les heures
  workflow_dispatch:      # Permet de le lancer manuellement pour tester

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests supabase
      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python update_prices.py
